name: Build & Test
on:
  - push
  - pull_request

jobs:
  BuildAndTest:
    name: ApplePlatforms
    runs-on: macos-latest
    strategy:
        matrix:
          scheme:
            - Bintrail macOS
            - Bintrail iOS
            - Bintrail tvOS
            - Bintrail watchOS
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: |
          set -o pipefail && env NSUnbufferedIO=YES xcodebuild clean test -project Bintrail.xcodeproj -scheme "${{ matrix.scheme }}" | xcpretty

  spm-macOS:
    name: Test Swift Package manager (macOS)
    runs-on: macos-latest    
    steps:
      - uses: actions/checkout@v1
      - name: swift test
        run: swift test