on:
  - push
  - pull_request
name: Build
jobs:
  carthage:
    name: Carthage
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Carthage build
        run: |
          carthage build --no-skip-current --verbose